### ISSUE TITLE
wevtutil output broken ( on Windows Server 2022 ? )

### ISSUE THREAD

**Issue by JMDirksen** [JMDirksen/BlockIP#1]
The command `wevtutil qe Security /c:2 /rd:true /f:text` is supposed to output the last 2 security log events, but only the first is complete the second event has "N/A" values.
Script will not register more than 1 bad login attempt now.

Windows Server 2022 Standard 21H2 20348.405

Output:

```
Event[0]
  Log Name: Security
  Source: Microsoft-Windows-Security-Auditing
  Date: 2021-12-25T07:33:18.1520000Z
  Event ID: 4625
  Task: Logon ?  Level: Information ?  Opcode: Info  ?  Keyword: Audit Failure  ?  User: N/A
  User Name: N/A
  Computer: micro
  Description: 
An account failed to log on.

Subject:
	Security ID:		S-1-0-0
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		S-1-0-0
	Account Name:		ADMINISTRATOR
	Account Domain:		

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC0000064
```

...

```
Event[1]
  Log Name: Security
  Source: Microsoft-Windows-Security-Auditing
  Date: 2021-12-25T07:31:58.8310000Z
  Event ID: 4625
  Task: N/A
  Level: N/A
  Opcode: N/A
  Keyword: N/A
  User: N/A
  User Name: N/A
  Computer: micro
  Description: 
N/A
```

**Comment by JeftaDirksen** [comment]
wevtutil on Windows 10 Enterprise 21H2 19044.1415 seems to work ok

wevtutil on Windows 11 Pro 21H2 22000.318 and 22000.376 show the same issue

**Comment by JeftaDirksen** [comment]
Issue reported @ Microsoft
https://techcommunity.microsoft.com/t5/report-an-issue/wevtutil-exe-outputs-n-a-values-when-multiple-results/m-p/3045729

**Comment by JeftaDirksen** [comment]
Doesn't seem to be an issue anymore
